#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p dist/artifacts
cp bin/ack-operator dist/artifacts/ack-operator-linux${SUFFIX}
for i in bin/ack-operator-*; do
    if [ -e "$i" ]; then
          cp $i dist/artifacts
    fi
done
